default_context:
  project_name: 'fastapi-pgres'
  project_slug: 'fastapi-pgres'
  domain_main: 'yfinance.dev'
  domain_staging: 'stag.yfinance.dev'
  docker_swarm_stack_name_main: 'yfinance-dev'
  docker_swarm_stack_name_staging: 'stag-yfinance-dev'
  secret_key: 'hunter2'
  first_superuser: 'sam@freighttrust.com'
  first_superuser_password: 'hunter3'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.yfinance.dev", "https://stag.yfinance.dev", "https://yfinance.dev", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@yfinance.dev'
  postgres_password: 'power-edge-stump-goofy-alias-wafer-gave'
  pgadmin_default_user: 'sam@freighttrust.com'
  pgadmin_default_user_password: 'omen-paper-trek-mull-vice-mumbo-wifi'
  traefik_constraint_tag: 'yfinance.dev'
  traefik_constraint_tag_staging: 'stag.yfinance.dev'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:hunter3'
  sentry_dsn: ''
  docker_image_prefix: 'sambacha'
  docker_image_backend: 'sambacha-backened'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
